import type { LayoutConfig } from "@/app/page"

// Generate a unique ID
const generateId = () => Math.random().toString(36).substring(2, 9)

export const defaultLayouts: LayoutConfig[] = [
  {
    id: "grid-3x3",
    name: "Grid 3x3",
    columns: 3,
    gap: 16,
    holders: [
      {
        id: generateId(),
        width: 100,
        height: 200,
        borderWidth: 0,
        borderColor: "#000000",
        borderRadius: 0,
        shadow: "none",
        padding: 0,
        backgroundColor: "transparent",
      },
      {
        id: generateId(),
        width: 100,
        height: 200,
        borderWidth: 0,
        borderColor: "#000000",
        borderRadius: 0,
        shadow: "none",
        padding: 0,
        backgroundColor: "transparent",
      },
      {
        id: generateId(),
        width: 100,
        height: 200,
        borderWidth: 0,
        borderColor: "#000000",
        borderRadius: 0,
        shadow: "none",
        padding: 0,
        backgroundColor: "transparent",
      },
      {
        id: generateId(),
        width: 100,
        height: 200,
        borderWidth: 0,
        borderColor: "#000000",
        borderRadius: 0,
        shadow: "none",
        padding: 0,
        backgroundColor: "transparent",
      },
      {
        id: generateId(),
        width: 100,
        height: 200,
        borderWidth: 0,
        borderColor: "#000000",
        borderRadius: 0,
        shadow: "none",
        padding: 0,
        backgroundColor: "transparent",
      },
      {
        id: generateId(),
        width: 100,
        height: 200,
        borderWidth: 0,
        borderColor: "#000000",
        borderRadius: 0,
        shadow: "none",
        padding: 0,
        backgroundColor: "transparent",
      },
      {
        id: generateId(),
        width: 100,
        height: 200,
        borderWidth: 0,
        borderColor: "#000000",
        borderRadius: 0,
        shadow: "none",
        padding: 0,
        backgroundColor: "transparent",
      },
      {
        id: generateId(),
        width: 100,
        height: 200,
        borderWidth: 0,
        borderColor: "#000000",
        borderRadius: 0,
        shadow: "none",
        padding: 0,
        backgroundColor: "transparent",
      },
      {
        id: generateId(),
        width: 100,
        height: 200,
        borderWidth: 0,
        borderColor: "#000000",
        borderRadius: 0,
        shadow: "none",
        padding: 0,
        backgroundColor: "transparent",
      },
    ],
  },
  {
    id: "featured",
    name: "Featured",
    columns: 2,
    gap: 16,
    holders: [
      {
        id: generateId(),
        width: 100,
        height: 400,
        borderWidth: 0,
        borderColor: "#000000",
        borderRadius: 0,
        shadow: "none",
        padding: 0,
        backgroundColor: "transparent",
      },
      {
        id: generateId(),
        width: 100,
        height: 190,
        borderWidth: 0,
        borderColor: "#000000",
        borderRadius: 0,
        shadow: "none",
        padding: 0,
        backgroundColor: "transparent",
      },
      {
        id: generateId(),
        width: 100,
        height: 190,
        borderWidth: 0,
        borderColor: "#000000",
        borderRadius: 0,
        shadow: "none",
        padding: 0,
        backgroundColor: "transparent",
      },
    ],
  },
  {
    id: "masonry",
    name: "Masonry",
    columns: 3,
    gap: 16,
    holders: [
      {
        id: generateId(),
        width: 100,
        height: 300,
        borderWidth: 0,
        borderColor: "#000000",
        borderRadius: 0,
        shadow: "none",
        padding: 0,
        backgroundColor: "transparent",
      },
      {
        id: generateId(),
        width: 100,
        height: 200,
        borderWidth: 0,
        borderColor: "#000000",
        borderRadius: 0,
        shadow: "none",
        padding: 0,
        backgroundColor: "transparent",
      },
      {
        id: generateId(),
        width: 100,
        height: 250,
        borderWidth: 0,
        borderColor: "#000000",
        borderRadius: 0,
        shadow: "none",
        padding: 0,
        backgroundColor: "transparent",
      },
      {
        id: generateId(),
        width: 100,
        height: 220,
        borderWidth: 0,
        borderColor: "#000000",
        borderRadius: 0,
        shadow: "none",
        padding: 0,
        backgroundColor: "transparent",
      },
      {
        id: generateId(),
        width: 100,
        height: 280,
        borderWidth: 0,
        borderColor: "#000000",
        borderRadius: 0,
        shadow: "none",
        padding: 0,
        backgroundColor: "transparent",
      },
      {
        id: generateId(),
        width: 100,
        height: 240,
        borderWidth: 0,
        borderColor: "#000000",
        borderRadius: 0,
        shadow: "none",
        padding: 0,
        backgroundColor: "transparent",
      },
    ],
  },
  {
    id: "classic",
    name: "Classic",
    columns: 1,
    gap: 24,
    holders: [
      {
        id: generateId(),
        width: 100,
        height: 300,
        borderWidth: 4,
        borderColor: "#ffffff",
        borderRadius: 0,
        shadow: "md",
        padding: 8,
        backgroundColor: "#f8f8f8",
      },
      {
        id: generateId(),
        width: 100,
        height: 300,
        borderWidth: 4,
        borderColor: "#ffffff",
        borderRadius: 0,
        shadow: "md",
        padding: 8,
        backgroundColor: "#f8f8f8",
      },
      {
        id: generateId(),
        width: 100,
        height: 300,
        borderWidth: 4,
        borderColor: "#ffffff",
        borderRadius: 0,
        shadow: "md",
        padding: 8,
        backgroundColor: "#f8f8f8",
      },
    ],
  },
  {
    id: "polaroid",
    name: "Polaroid",
    columns: 3,
    gap: 24,
    holders: [
      {
        id: generateId(),
        width: 100,
        height: 220,
        borderWidth: 8,
        borderColor: "#ffffff",
        borderRadius: 2,
        shadow: "lg",
        padding: 0,
        backgroundColor: "#ffffff",
      },
      {
        id: generateId(),
        width: 100,
        height: 220,
        borderWidth: 8,
        borderColor: "#ffffff",
        borderRadius: 2,
        shadow: "lg",
        padding: 0,
        backgroundColor: "#ffffff",
      },
      {
        id: generateId(),
        width: 100,
        height: 220,
        borderWidth: 8,
        borderColor: "#ffffff",
        borderRadius: 2,
        shadow: "lg",
        padding: 0,
        backgroundColor: "#ffffff",
      },
      {
        id: generateId(),
        width: 100,
        height: 220,
        borderWidth: 8,
        borderColor: "#ffffff",
        borderRadius: 2,
        shadow: "lg",
        padding: 0,
        backgroundColor: "#ffffff",
      },
      {
        id: generateId(),
        width: 100,
        height: 220,
        borderWidth: 8,
        borderColor: "#ffffff",
        borderRadius: 2,
        shadow: "lg",
        padding: 0,
        backgroundColor: "#ffffff",
      },
      {
        id: generateId(),
        width: 100,
        height: 220,
        borderWidth: 8,
        borderColor: "#ffffff",
        borderRadius: 2,
        shadow: "lg",
        padding: 0,
        backgroundColor: "#ffffff",
      },
    ],
  },
  {
    id: "modern",
    name: "Modern",
    columns: 2,
    gap: 20,
    holders: [
      {
        id: generateId(),
        width: 100,
        height: 250,
        borderWidth: 0,
        borderColor: "#000000",
        borderRadius: 16,
        shadow: "md",
        padding: 0,
        backgroundColor: "transparent",
      },
      {
        id: generateId(),
        width: 100,
        height: 250,
        borderWidth: 0,
        borderColor: "#000000",
        borderRadius: 16,
        shadow: "md",
        padding: 0,
        backgroundColor: "transparent",
      },
      {
        id: generateId(),
        width: 100,
        height: 250,
        borderWidth: 0,
        borderColor: "#000000",
        borderRadius: 16,
        shadow: "md",
        padding: 0,
        backgroundColor: "transparent",
      },
      {
        id: generateId(),
        width: 100,
        height: 250,
        borderWidth: 0,
        borderColor: "#000000",
        borderRadius: 16,
        shadow: "md",
        padding: 0,
        backgroundColor: "transparent",
      },
    ],
  },
]
